[package]
name = "libsvm"
version = "0.1.0"
authors = ["Kelvin Ly <kelvin.ly1618@gmail.com>"]

[dependencies]
libsvm_sys = { path = "libsvm-sys" }
libc = "0.2"

[build-dependencies]
gcc = "0.3"

[workspace]
